### ISSUE TITLE
Move blockchain package to a separated repo?

### ISSUE THREAD

**Issue by JFixby** [decred/dcrd#1228]
No specific issue, just a question/suggestion:

The readme says ```This package has intentionally been designed so it can be used as a standalone package for any projects needing to handle processing of blocks into the decred block chain.```

Does it make sense to move the package to a separated repo for a better code maintainability?

**Comment by davecgh** [comment]
A long time ago we actually had all of the packages in separate repositories, but it really made it much more difficult to track important changes, so we combined all of the packages into the same repository.

Also, with the upcoming [versioned toolchain vgo](https://github.com/golang/go/wiki/vgo) which is going to replace the existing `go` command, there will no longer be any need to have packages in a separate repository from this perspective because it does a good job of supporting multiple modules within the same repository.

Given those two things, I personally would much rather keep it in the main repository.

**Comment by JFixby** [comment]
Thank you for the explanation.
