### ISSUE TITLE
can not create a srcitp hash address.  And How to use it?

### ISSUE THREAD

**Issue by zhaoyulong1** [decred/dcrd#1386]
![123](https://user-images.githubusercontent.com/13092764/43810966-e852be9e-9aec-11e8-94d4-cde535316673.png)
![2141](https://user-images.githubusercontent.com/13092764/43810968-ebfde2e4-9aec-11e8-906c-05b3c3834205.png)

**Comment by davecgh** [comment]
I'm not 100% sure what you're asking.  For `NewAddressScriptHash`, you just give it the serialized script you want to pay to, as the parameter indicates.  That means you first create the script that you want, then serialize it, and pass it in.

If you're not familiar with how to create scripts, then you really don't want to use a pay-to-script-hash, because you could easily end up with a script that would allow people to steal the funds if you aren't careful.

**Comment by zhaoyulong1** [comment]
thanks for your response. I really want to create it and use a pay-to-script-hash. As you said I must have a script to put in method .  But I can not find how to make it in the project or wallet ,dcrctl command .  Can you help me ? very thanks

**Comment by zhaoyulong1** [comment]
or Do you have other method to produce it ?           And after i create it ,how can i use it in the wallet or dcrctl to make a transaction?

**Comment by zhaoyulong1** [comment]
I have create a  script address  but I can not spent money in it .   can not find a tool or a better method .

**Comment by zhaoyulong1** [comment]
![6 3lzowfkc3ijrhm wnn h](https://user-images.githubusercontent.com/13092764/43890705-01760fc6-9bfa-11e8-8347-c8b59f37713f.png)
![d b38 u hndem pd7evd4eu](https://user-images.githubusercontent.com/13092764/43890706-0349002e-9bfa-11e8-9d30-dc7d2daceb39.png)

**Comment by zhaoyulong1** [comment]
can close  this ,I find commod in ctl to create  and use it.  thanks!
