### ISSUE TITLE
sendTransaction:  stack underflow

### ISSUE THREAD

**Issue by jtomtan** [decred/dcrd#1486]
Hi DCR developers:

we got an exception in our sever logs when our users use BITBILL wallet to send DCR. We think this could be a bug of dcrd server. It happened just once. The exception message is as below:

sendTransaction - Rejected transaction 039d14eaa4c7cb9ca6bdbc526390cb55323cbef009050a5b850c911ab1fd6380: failed to validate input 039d14eaa4c7cb9ca6bdbc526390cb55323cbef009050a5b850c911ab1fd6380:0 which references output 3f3c9c47e329433987ee52567707accffc450b185ce2f251e24a1046662248ae:26 - stack underflow (input script bytes , prev output script bytes 76a9144a82da82dca1653d38ba3b2afeb8f8a384e4baf988ac)

So, would you please check it?

**Comment by davecgh** [comment]
It was rejected (as it should have been) because your signature script is empty.  Notice that it does not have any input script bytes.  That means the transaction that was provided did not have anything set for the `SignatureScript` which is necessary to redeem the previous output script.

Per the error message, that output script of the reference txout is `76a9144a82da82dca1653d38ba3b2afeb8f8a384e4baf988ac`, which is a standard p2pkh output as seen by decoding the script:

```
$ dcrctl decodescript 76a9144a82da82dca1653d38ba3b2afeb8f8a384e4baf988ac
{
  "asm": "OP_DUP OP_HASH160 4a82da82dca1653d38ba3b2afeb8f8a384e4baf9 OP_EQUALVERIFY OP_CHECKSIG",
  "reqSigs": 1,
  "type": "pubkeyhash",
  "addresses": [
    "DsXktFVQkTWyKCY2auEnA6V7XsttKvE3HNy"
  ],
  "p2sh": "Dcq8QPojkrivD1p3RBeVQuYPTY7S6Rn4ZVM"
}
```

Thus, your `SignatureScript` should have been providing the signature and public key, and it didn't.

**Comment by davecgh** [comment]
I would guess that the wallet probably failed to produce a signature for whatever reason, and instead of handling the error, it just tried to send the unsigned transaction.

**Comment by jtomtan** [comment]
Yes, it's our bug. We are trying to fix it. Thanks for the answer.
