### ISSUE TITLE
Proper way to use simnet?

### ISSUE THREAD

**Issue by jseibel-circle** [decred/dcrd#1537]
I'm trying to use the simnet to do a flow of generating blocks and sending coins. On other blockchains, using regtest is straightforward. I believe the ticket PoS system is making this difficult to figure out.

The issue is that at block 150, I can't get past a fork that occurs. The message is always like: `FORK: Block 0000237c2315a985aee5e7042649abecb335db123f295bb6298a7779d41cb319 (height 150) forks the chain at height 149/block 00007cf7d956ba5261aecad2e437181f3edd696cae9c33254723132088a8aadc, but does not cause a reorganize`.

Every time I try to generate a new block, it always gives this message, and I'm always stuck at block 150.

I've tried several things like purchasing tickets before generating blocks, sending transactions, etc. but nothing gets past it.

What is the proper way to exercise the blockchain using simnet?

I start both dcrd and dcrwallet with `--simnet`

My dcrd.conf:
```
appdata=/data-e/data
datadir=/data/.dcrd
logdir=/data-e/
rpclisten=127.0.0.1:9109
rpcuser=[removed]
rpcpass=[removed]
txindex=1
notls=true
miningaddr=Sss2TKuna7q9PdKZ9T4Co6k24qezAhY7fgx
acceptnonstd=1
blockminsize=0
```

dcrwallet.conf:
```
pass=[removed]
appdata=/data/.dcrwallet
rpcconnect=127.0.0.1:9109
rpclisten=127.0.0.1:9110
rpcmaxclients=30
dcrdusername=[removed]
dcrdpassword=[removed]
username=[removed]
password=[removed]
debuglevel=info
nogrpc=true
noservertls=true
noclienttls=true
enablevoting=1
enableticketbuyer=1
reuseaddresses=1
```

**Comment by davecgh** [comment]
You're very likely not buying tickets and thus the chain can't continue because it can't get any votes (since there are no tickets being purchased to choose from).

You should setup the ticket buyer on your wallet.

[Here is a gist](https://gist.github.com/davecgh/3da3c48bd9ab1914ff134c0b26b8661c) that sets up a 2-node simnet network with a wallet configured to use the ticket buyer using tmux and provides some useful scripts for more easily interacting with them.

**Comment by jseibel-circle** [comment]
Thanks for your quick response. My setup has both a dcrd daemon node and a dcrwallet wallet node. The wallet is configured like I posted above. I added the additional missing config (`ticketbuyer.*` values) and still have the same issue.

From looking at the gist you posted, essentially you are

- Setting up a mining node
- Setting up 2 wallet nodes
- Wallet nodes each have a script (`tickets`)that purchases 300 tickets and assigns voting rights to random new address
- Wallet nodes each have a script (`xfer`) that sets a random tx fee, transfers money to a specific address, then sets txfee back to 0.001
- Mining node has a script to generate (mine) set number of blocks with a sleep between each

I assume what you are supposed to do is to purchase tickets from each node then mine blocks to confirm them. Is it important to have 2 different wallet nodes? I am doing this flow right now with a single mining node and single wallet node. I will also get a second node started to see if that helps.

**Comment by davecgh** [comment]
You'll have to reset your simnet setup if it's in the state where there aren't enough tickets.  Once you have gone past the point of no return, so to speak, you can't recover, so just adding the ticketbuyer options to a setup that is already in that state won't allow it to recover.

As far as what the gist is doing, you have it most correct, except it's setting up a mining node, one wallet, and a second client node.  You don't really need the second node, I just pointed you at the gist because I know for sure the setup works with the latest master versions of dcrd and dcrwallet, since I personally use it all the time as it's much easier to reset the setup for new test scenarios and the scripts like `mine`, `ctl`, `tickets`, and `xfer` are nicer than typing the full commands out when you're doing it all the time.

The important part is that you should see the wallet purchasing at least 5 tickets per block (because there is only one wallet on the network and each block needs 5 votes, you'll run out eventually if you're not replenishing the tickets).  You can see if tickets are being purchased by checking `./ctl getrawmempool false tickets` and the current live tickets with `./ctl livetickets`.

**Comment by jseibel-circle** [comment]
I think I'm understanding. To clarify a few things:

- Turning on ticket buyer in the wallet node will not automatically purchase tickets each block. So if I set `ticketbuyermaxperblock=5`, then mine 100 blocks, it will not automatically buy 5 every block.
- `ticketbuyer.maxinmempool` sets how many tickets are in the mempool. SO as this defaults to 40, there will never be more than 40 unless I increase it.
- Is there any way to make it so that there is enough tickets so that I could mine, say, 500 blocks without worrying about running out of tickets?
- The idea is that every block, at least 5 tickets are purchased. Are those tickets only valid for that specific block?

Sorry for all the questions, I can't seem to figure these questions out from the doc, probably my fault.

**Comment by davecgh** [comment]
Not quite. I should've clarified that it really depends on the version.  The current latest released versions of dcrd/dcrwallet did not support the newer simplified v2 ticket buyer with simnet.  If you're running master on both, however, it is supported.

Those additional parameters are actually forcing the v1 ticket buyer to activate.  If you're running master on both though, you can use only `enableticketbuyer=1` and it'll work as expected.  However, if you're not running the latest master branch, those additional options essentially force it to the v1 ticket buyer.

Your descriptions are accurate for v1 ticket buyer, and as noted, if you use any of those options, it force v1 ticket buyer.

As far as tickets, you can purchase a bunch of tickets in bulk, but do keep in mind that there is a max of 20 new tickets allowed per block and the ticket price changes periodically, hence the best option is to just use the ticket buyer and allow it to continuously buy tickets for you.

So, for the easiest use:

* Make sure you're running master branch of dcrd and dcrwallet
* Ensure you have `enableticketbuyer=1` and `enablevoting=1` in  your wallet config and no other `ticketbuyer.X` options since that will force v1 ticket buyer
* Ensure you have the wallet unlocked as it can neither buy new tickets nor vote if it's locked (e.g. `pass=` in the config
* Make sure you mine a block (e.g. block 1) _before_ you start the wallet.  If you don't do this you will have issues
  * In fact, I suggest mining 32 blocks before you start the wallet so that you immediately have matured funds available to buy tickets.  You'll notice the gist I linked does just that.
* Make sure you wait a little bit of time in between mining each block to give the wallet time to vote and buy new tickets.  Again, you'll notice the `mine` script in the linked gist includes a sleep for that purpose.

**Comment by davecgh** [comment]
I updated the linked gist for the latest master as well.

**Comment by jseibel-circle** [comment]
Thank you, this worked for me. Not sure if you can also help with another problem I'm having https://github.com/decred/dcrwallet/issues/1333 ?

But thanks so much for your time and effort! Valuable information
