### ISSUE TITLE
does decred support  multisignature?

### ISSUE THREAD

**Issue by qq976739120** [decred/dcrd#1557]
who knows?I found no specific instructions in the documentation, but there were methods called in the repository

**Comment by davecgh** [comment]
Yes, it's pretty much the same as all other script-based coins.  You'd have to be much more specific regarding what you're trying to accomplish however to give any more details since it largely depends on the method by which you're creating transactions given there are a multitude of ways to do it.

**Comment by qq976739120** [comment]
> Yes, it's pretty much the same as all other script-based coins. You'd have to be much more specific regarding what you're trying to accomplish however to give any more details since it largely depends on the method by which you're creating transactions given there are a multitude of ways to do it.

There are some simple methods, such as direct call RPC, jsonrpc, restfull, like XRP and XLM,The document seems to have no relevant instructions. Did I not read it carefully?

**Comment by matheusd** [comment]
As a starter, if you're trying to create from the command line, try looking at the available multisig actions:

`dcrctl -l | grep multisig`

Using the json rpc endpoint, the process is largely the same, except you'll use direct calls to the service instead of the command line app.

https://godoc.org/github.com/decred/dcrd/dcrjson#CreateMultisigCmd

**Comment by qq976739120** [comment]
@matheusd thanks!

**Comment by jrick** [comment]
If you still have questions about how to create multisig output scripts, it would be more efficient to ask those on one of our [community platforms](https://decred.org/community/)
