### ISSUE TITLE
How to use the RPC server  if I want to connect to the node with another machine ? 

### ISSUE THREAD

**Issue by zhangliang7190** [decred/dcrd#1558]
I use --notls to connect the dcrd and poolserver in a local machine.
but if I don't use --notls ,I can't connect dcrd with another machine.How I should do it? I need deliver the dcrd and poolserver into different machine.
Thank you very much !

**Comment by davecgh** [comment]
You have to add your external IP address to the certificate if you want to allow remote connections.  The ability to connect remotely without TLS is intentionally disallowed because that is horribly insecure.

If you're using version 1.4.0-rc1, delete the existing `rpc.cert`/`rpc.key` and start dcrd with `--altdnsnames` along with the external IP address (or DNS name if it has a public one) of the machine you wish to expose.  Then, you'll have to copy the newly generated `rpc.cert` file over to the machine you are connecting from and make sure whatever software you're using to connect with is configured to use the certificate.

**Comment by zhangliang7190** [comment]
> You have to add your external IP address to the certificate if you want to allow remote connections. The ability to connect remotely without TLS is intentionally disallowed because that is horribly insecure.
> 
> If you're using version 1.4.0-rc1, delete the existing `rpc.cert`/`rpc.key` and start dcrd with `--altdnsnames` along with the external IP address (or DNS name if it has a public one) of the machine you wish to expose. Then, you'll have to copy the newly generated `rpc.cert` file over to the machine you are connecting from and make sure whatever software you're using to connect with is configured to use the certificate.

👌，I just have a try .
