### ISSUE TITLE
thresholdstate: Why not use prevNode.stakeVersion ?

### ISSUE THREAD

**Issue by lealife** [decred/dcrd#1693]
https://github.com/decred/dcrd/blob/c0e74f5ffac1e68c9da5c295779164a5815c2a25/blockchain/thresholdstate.go#L306-L310

I have a question:

Why not use `prevNode.stakeVersion` to replace `b.calcStakeVersion(prevNode)` ?

**Comment by davecgh** [comment]
In order to move to the started voting state, the new stake version associated with the vote must have first been voted in.  If you were to just replace that, it would entirely break the upgrade logic.  You can easily convince yourself of this by making the suggested change and running the tests.  You will see a mountain of failures.

**Comment by lealife** [comment]
From https://github.com/decred/dcrd/blob/master/blockchain/validate.go#L1153-L1165

We know `currentNode.stakeVersion == b.calcStakeVersion(prevNode)`

So we can take the next Node's  stakeVersion to replace the code:

```
                         // Get stake version from next node
			// if next node is nil, then re-calculate it
			nextBlockHeader, err := b.HeaderByHeight(prevNode.height + 1)
			var stakeVersion uint32
			if err == nil {
				stakeVersion = nextBlockHeader.StakeVersion
			} else {
				stakeVersion = b.calcStakeVersion(prevNode)
			}

			// Make sure we are on the correct stake version.
			if stakeVersion < version {
				stateTuple.State = ThresholdDefined
				break
			}
```
I test `/blockchain` and all is passed.

**Comment by davecgh** [comment]
It only passed because there isn't a test of a reorg large enough with different stake version to hit the particular bug that would introduce.  If you take a look at `HeaderByHeight`, you'll see that it returns the [header *on the main chain*](https://godoc.org/github.com/decred/dcrd/blockchain#BlockChain.HeaderByHeight), but there is guarantee here that you are already on the main chain.

**Comment by lealife** [comment]
Thanks very much, i got it!!
