### ISSUE TITLE
orphan block，Contains duplicate transaction information

### ISSUE THREAD

**Issue by Seymour-w** [decred/dcrd#1700]
hi all,
Why do duplicate trading messages appear? What causes it?
https://mainnet.decred.org/block/0000000000000000263390e34270c07f3a64762782da2257daaf7445f4862d54

Thanks!

**Comment by matheusd** [comment]
That block has been reorged out of the mainchain. While it says "mainchain" in insight, that block is not part of the current mainchain as can be seen from dcrdata:

https://explorer.dcrdata.org/block/312793

**Comment by Seymour-w** [comment]
Thx! I want to know the reason of this phenomenon.  Need to ensure the uniqueness of the transaction information.

**Comment by matheusd** [comment]
Reorganizations of the block chain, specially one-block long ones is a relatively common occurrence and happens when 2 different miners find a solution to a block at a very close interval to one another.

This seems to be the case here, given that the immediately previous block 312792 is the same on both the current mainchain and the block you pointed to _and_ the timestamp for both blocks is pretty close to one another (though that is not hard evidence since there's some wiggle room for timestamps to vary and they aren't necessarily accurate to the second).

Around this time (jan/2019) we were also experiencing some issues due to a hard forking bug (see https://github.com/decred/dcps/blob/master/dcp-0004/dcp-0004.mediawiki and https://matheusd.com/post/dcp0004-and-hardforks/) so this particular block could have been generated due to that (though a quick review of the txs on each block doesn't show any differences).

**Comment by Seymour-w** [comment]
Hi matheusd, Thank you for your interpretation.
