### ISSUE TITLE
Updated to 1.4.0, reindexing fails

### ISSUE THREAD

**Issue by Crypto2** [decred/dcrd#1722]
2019-04-18 21:59:26.099 [INF] CHAN: Reindexing block information in the database.  This will take a while...
2019-04-18 21:59:27.891 [ERR] DCRD: Unable to start server on [:port]: block data for block 0000000000003777f9973aab5686089faf9fe70692cd8fe8030b4bf4a04a9c12 checksum does not match - got da5dac4b, want 0

**Comment by davecgh** [comment]
That means your database is corrupt.  You'll have to remove the chain and let it download again.

**Comment by Crypto2** [comment]
That's what I ended up doing. The main thing in this report is that the only thing that happened was a node update so there is some kind of bug between the versions that it isn't able to read the older chain DB forcing a redownload + more downtime.

**Comment by davecgh** [comment]
That particular error can only happen when the raw block data on disk is changed in some way (aka the corruption I mentioned).  It really wasn't the case of a bug between the versions, it's the case that you never hit an error previously because there was nothing attempting to access the corrupted data.  The upgrade to 1.4.0 involves a reindexing operation which necessarily accesses every single block in order to reindex it.

I don't recommend doing it, but for completeness of explanation and to provide an example that definitely shows this behavior, you could make a backup of your current blockchain data and then open up the `~/.dcrd/data/mainnet/blocks_ffldb/000000000.fdb` which houses the raw block data with a hex editor and change a single byte somewhere in block 1, such as changing offset `0x1f5` to the value `0x00` in order to intentionally corrupt the block.

Then, you will notice that if  you restart `dcrd`, everything will appear fine and continue to work as expected because nothing is accessing that block.  However, then if you perform a command such as `$ dcrctl getblockhash 1 | dcrctl getblock -` in order to access the block, you'll get an error indicating the block is not found because it is now corrupted (the RPC server assumes all errors mean the block doesn't exist, but it's really getting a checksum error).  Meanwhile, running `$ dcrctl getblockhash 1 | dcrctl getblockheader -` will still work properly because the header is stored elsewhere and is still intact.

If you were to then change the intentionally corrupted value back to the original value of `0x01` and run the same command, it would work properly again.
