### ISSUE TITLE
release-v1.4.0 can not be built without replaces

### ISSUE THREAD

**Issue by jrick** [decred/dcrd#1738]
```
$ GO111MODULE=on go get github.com/decred/dcrd@release-v1.4.0
go: finding github.com/decred/dcrd release-v1.4.0
# github.com/decred/dcrd
go/pkg/mod/github.com/decred/dcrd@v1.2.1-0.20190128173639-e3e8c47c68b0/server.go:2557:4: unknown field 'AcceptSequenceLocks' in struct literal of type mempool.Policy
```

We should start pulling out replaces for releases.  In this case, it hid a bug in the requires.  By fixing this we would gain the same build when doing the above `go get` process as well as building from within the directory, and it would become possible for users to `go get` particular releases.

**Comment by davecgh** [comment]
I agree with the concept here and, in fact, all of the individual modules except for the root have already had the replaces removed and all future release branches will remove all root module overrides which means this will work.

Unfortunately, those changes all happened after the `release-v1.4.0`, so in order to make it work for the existing `release-v1.4.0` branch, we'd have to backport all of those changes into the branch.  We could do that, but the plan was to just cut over as of `release-v1.5.0`.
