### ISSUE TITLE
rpcclient: add OnClientDisonnected notifications

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrd#1877]
For a client who wants to know what happened between a disconnect and reconnect, there is no good way for a client to correctly ascertain when the disconnect happened.  We need an OnClientDisconnected notification to go along with the OnClientConnected notification that already exists.

**Comment by deepsi43** [comment]
Hi,just checking if this issue has been addressed.And would also like to know if someones already working the referenced rpcclient package issues being mentioned .

**Comment by JoeGruffins** [comment]
@deepsi43 It is open and no one is on it yet. These issues are new.

@davecgh would like you opinion on these rpcclient issues if you have time. Thanks.

**Comment by davecgh** [comment]
I don't believe this is the right way to go about it because there is no way to guarantee that the disconnected message coincides with when the disconnect actually happened.  This is an extremely standard issue with network connections in general.  The remote might have disconnected a while ago without sending a FIN/RST (maybe it lost power, maybe the previous route become invalid due to a router along the path going offline, etc).

The proper way to handle this is always client side.  The client simply needs to keep track of where they are and, upon a new connection, react accordingly.

**Comment by davecgh** [comment]
To elaborate, the only proper and safe way to handle this is by analyzing the chain lineage.

For example, let's say a client is tracking the chain and they are currently at block 377173 with hash 000000000000000014b2042c81f9a306cf570c487676c0eb6a56337eeb067bde.  A disconnect happens at some point.

Upon reconnect, the client needs to check the current chain tip of the remote to figure out if it has changed in between.  When it has, the client needs to consider the following cases:

- The current remote tip height is the same, but block hash is different.  This means a reorganize happened, so the client needs to disconnect its tip and connect the new one.
- The current remote tip height is higher and the local tip is an ancestor of the new tip.  This means the chain has advanced and the client can simply fast forward to the most recent block
- The current remote tip height is higher and the local tip is *NOT* ancestor of the new tip.  This also means a reorganize happened, so the client needs to disconnect its tip back to the fork point and connect the new ones on the new branch
- The current remote tip height is lower.  This means the remote was likely nuked and/or otherwise manually modified to revert the chain to some point in history.  The client can choose how to handle this in a few of ways, but the most standard way would be to determine if the current remote tip is an ancestor of the current local tip and react accordingly.  In the case it *is* an ancestor, it can wait for the remote to catch up.  In the case it is *NOT* an ancestor, the client will need to disconnect all the back to the fork point, just like in the reorganize case.

Notice that all of these things are 100% required independent of knowing when a disconnect happened.  That heavily implies having an `OnClientDisconected` , even if it weren't completely flaky as previously described, is a complete misfeature.

**Comment by JoeGruffins** [comment]
@davecgh Thank you. This needs to be put is a book somewhere.

Any thoughts on: https://github.com/decred/dcrd/issues/1876
and: https://github.com/decred/dcrd/issues/1878

@deepsi43 I will be closing this issue.

**Comment by chappjc** [comment]
Checking the chain state on reconnect is certainly a part of this.  We've gone over some of the bullets on the chain tip (but far less eloquently).

But I'm looking at the notification issue from a different perspective.  While the consumer of rpcclient has to handle chain state in the way that is appropriate for them, rpcclient can help identify both cleanly closed and lost connections.  For the former, rpcclient (who owns the actual gorilla websocket) will know immediately when the server shuts down cleanly, thus sending a `close` control frame.  Only rpcclient will know about this, and that's where I think something like `OnServerHangup` would be helpful to be more promptly notified when the connection is down.  The later case where the server just vanishes without saying goodbye (for whatever reason), that's where a configurable ping/pong feature for rpcclient would be helpful.  I also imaging that when rpcclients pings are not met with a pong from the server within a configurable timeout, the same or different ntfn could be triggered.

To be clear, the reconnect ntfn is all that's needed to tell the rpcclient consumer to check chain state, but I think we're after a mechanism for the client to promptly switch into an offline mode for other reasons.

**Comment by deepsi43** [comment]
@JoeGruffins ok

**Comment by davecgh** [comment]
The problem is that this, and the other recent discussions, are, unfortunately, encouraging bad design decisions based on faulty assumptions of how networking works.  There is a reason `rpcclient` doesn't give you that information and it is because it is simply not reliable and it doesn't want to encourage flaky design.

If the client wants control over connection state, it needs to disable the config options for connection handling by `rpcclient` (e.g. `DisableConnectOnNew` and `DisableAutoReconnect` and deal with it itself.

I know from the past, and it's even evident in this thread, that the mere existence of a misleading notification like that leads to poorly designed code that intermittently fails and causes a barrage of issues to be created blaming the client for not always notifying properly, etc.

I have been thinking for a while that `rpcclient` probably needs to be reworked in general to just provide the nice bidirectional jsonrpc to concrete types adapter code and leave the connection handling semantics to the consumer.

I would much rather go that direction than adding things that *will* lead to incorrect code.

**Comment by chappjc** [comment]
Perhaps I jumped into a conversation with a different interest for such a feature.  But I don't think this idea is much about keeping track of chain state or even knowing exactly when the disconnect happened.

If you have an rpcclient driven client and an rpc server connected, but with no network issues between the two, and then the server shutsdown cleanly, the websocket server sends a Close frame and the client knows it.  This is helpful in a process like dcrdata where you'd want to display that connection state on a status page or preemptively blocking RPC requests for the sake of avoiding longish timeouts on requests.  Pinging is another option, but I just don't understand the harm of a notification when rpcclient internally is aware that the connection is lost.  Documenting that the notification the absence of the notification does not mean the connection is still live would seem to rule out any misinterpretations.

Together with a built-in ping/pong, it seems all the more useful to me.

**Comment by chappjc** [comment]
For reference the discussion about disconnect/reconnect started here: https://matrix.to/#/!LmKzrmxJIXNHNiEmIh:decred.org/$156754260519704lyPlo:decred.org?via=matrix.org&via=decred.org&via=zettaport.com

I was evidently unaware of the reconnect notification at the time.

> chappjc
>
> >  Say you lose the dcrd connection at some point, while you are disconnected any number of blocks may be mined or a reorg may happen, then rpcclient reconnects and you have no idea what has happened while disconnected.
> > You don't even know that rpcclient reconnected, except for logs
> > Because there's no notifications to tell dcrdata (or whatever is using rpcclient) when the disconnect or reconnect occurs
> > And missed notifications don't get sent from dcrd -> dcrdata
> > dcrd could queue them, but how is it to know if the client will ever return?
> 
> JoeGruff
> > So what's needed is, notifications for connect, reconnect, after a reconnect dcrdata can query the chain state to see what happened
> 
> chappjc
>
> > For disconnect and reconnect, yes.
> > dcrdata can start by checking that dcrd's best block (by hash!) is the same as dcrdata's
> > If not, see if dcrd's best is a direct descendent of dcrdata's, in which case dcrdata can simple fast forward (sync).
> > If dcrd's block is NOT a direct descendent of dcrdata's, then a reorg happened.

I still think disconnect notifications are useful, but as far as maintaining coherent chain state, the reconnect is all that matters as we've described.  I'm referring to a sequence "initial connect, disconnect, reconnect" to be clear.

The discussion around disconnect became more relevant while speaking with jrick about how he has dcrwallet tear down the syncer process when it is aware of a disconnect.  Such a thing is not possible with rpcclient because we don't have all the information that rpcclient has internally (and it's not polling).

**Comment by jrick** [comment]
In wsrpc I achieve this with these two methods:

https://godoc.org/github.com/jrick/wsrpc#Client.Done

https://godoc.org/github.com/jrick/wsrpc#Client.Err

The client will be associated with some error after a tcp termination, server hangup, client hangup, or a client notification processing error.  The Err method blocks until the final error is ready to be read.  Done will block until the error is ready to be read as well and is useful in multi-channel selects or selects with a default case.

After a client has errored for any reason, it cannot be reused.  A new client must be created to continue making RPC calls, even to the same server.

I don't mean to shill my own lib here, but this provides the properties believe @chappjc is asking for for disconnect detection, as well as providing an interface suitable for creating an adapter package like what @davecgh is considering.
