### ISSUE TITLE
Split wallet JSON-RPC things out of dcrd repo

### ISSUE THREAD

**Issue by jrick** [decred/dcrd#2133]
This is a write-up of a problem and a solution that was discussed in the #dexdev channel starting here: https://matrix.to/#/!EzTSRQITaqHuFBDFhM:decred.org/$caDFbEoWln4zlY8CekWnlhX42qFkdozH5knJ8Omt4bQ?via=decred.org&via=matrix.org&via=zettaport.com

Currently, there are two things in the dcrd repo which are dealing with dcrwallet JSON-RPCs: the dcrctl executable and the rpcclient package.  rpcclient is in its own submodule, while dcrctl is part of the dcrd main module.

Dcrwallet was changed to be a single module covering all packages in the repo (decred.org/dcrwallet), and therefore requiring this module to import its JSON-RPC types package in dcrctl means that the dcrd main module must transitively require things that the wallet also requires.  While this does not affect the package dependency graph, it does mean that requiring a new dcrwallet may hoist some shared dependencies between the projects and negatively affect dcrd.

The root problem leading to this situation is that things in the dcrd repo, and more specifically in dcrd's main module, are importing wallet packages for JSON-RPC support.  Splitting this support outside of the repo and/or module and moving wallet RPC support to the wallet module means a smaller module requirement graph for dcrd.

In the case of dcrctl, there are two possible solutions: either a submodule can be created from the package, or (my preference) the client is moved to another repository.  I suggest a separate repository because I expect it to cause less confusion, since it would be otherwise impossible to build dcrctl from dcrd's root directory as is possible today.

For rpcclient, I suggest removing all of the methods that are unique to dcrwallet.  To replace these calls, a package will be added to the dcrwallet module that wraps a minimal interface of RawRequest and/or RawRequestAsync methods, which rpcclient.Client implements, to provide a client variable that can the convenience methods on the wallet.  In the situation where a consumer wishes to call both dcrwallet methods, and dcrd methods through passthrough, they would create a rpcclient.Client dialing the wallet, and use wallet's package to create a second client wrapping this rpcclient.Client.  Both of these clients can be struct embedded into a single variable that has the combined set of methods from both servers.

**Comment by xaur** [comment]
Linking some related work:

- the new repo: https://github.com/decred/dcrctl
- multi: Split dcrctl to own repo and update docs (https://github.com/decred/dcrd/pull/2175)
- rpcclient: Remove dcrwallet methods (https://github.com/decred/dcrd/pull/2178)
- multi: Run go mod tidy on all modules. (https://github.com/decred/dcrd/pull/2185)
- client package for type-safe dcrwallet JSON-RPC calls (https://github.com/decred/dcrwallet/pull/1726)
- Add dcrctl to projects (https://github.com/decred/dcrdevdocs/pull/72)

**Comment by xaur** [comment]
I love the idea to have dcrctl in its own repo. It being in dcrd (especially the wallet stuff) was odd for a long time and now things are much cleaner. iirc this also breaks the cycle between dcrd and dcrwallet.

Thinking further, the whole chain vs wallet ctl program and RPC client issues seem to come from the design where chain daemon and wallet daemon are separate (which is good), _but_ we are trying to create a single point of control for _both_,  be it an RPC client library or a ctl program. But what if we don't do that and let the separation "propagate" further and yield two separate binaries and two separate RPC clients? Would the benefits outweigh the drawbacks (like the effort required for this change, having to use two binaries, having to use two RPC client variables, etc)? 

At the cost of having two programs and two RPC client variables in code, this would cleanly separate things further and even allow to host the RPC client and the ctl program in dcrd/dcrwallet repos respectively. This will address the confusion/convenience issue that @davecgh [pointed out](https://matrix.to/#/!EzTSRQITaqHuFBDFhM:decred.org/$gEdLydIhk_kidAFL5gKCqVZQzky7oWNL-xQclV1jOFs):

> dcrd can't reasonably be controlled or queried without it and forcing people to know they need to go to another repo to install a separate tool to interact with it is not ideal. It wasn't quite the same for dcrwallet for a long time because it required dcrd, but with SPV, I totally concede that same logic more and more applies to wallet too.

@chappjc I wonder how the dcrdex project is handling this since they also have two daemonds (server and client), both having their own RPC servers, and both needing command-line programs to control them through those RPC servers (and corresponding RPC clients). Do you guys have two ctl programs or one?

Of course changing everything once again would be a whole another round of churn but I'm just asking about theory now.

**Comment by xaur** [comment]
UX-wise, two binaries might in fact be easier to use. I can only speak for myself, but I often experience a small confusion between adding and not adding the `--wallet` switch, to the point that I'm considering `dctl` and `wctl` wrapper scripts.

**Comment by jrick** [comment]
This work has been completed so we can close this issue now.

@xaur fair points about having two client programs.  That was another option I considered but based on some earlier discussions about this, others weren't thrilled at the idea of two separate client programs.

With dcrctl now split out, I think we should leave it be for the time being and not jump to even more invasive tooling changes, especially as doing two different clients will break existing users of our binary releases (not just those who are building the tools from source and have to find the new repo).

**Comment by xaur** [comment]
Linking another relevant discussion on [2020-04-28](https://matrix.to/#/!HEeJkbPRpAqgAwhXWO:decred.org/$158809417750bMBFw:zettaport.com) that announces the change and lists pros and cons of extracting dcrctl into its ownr repo vs extracting rpc/json/types into its own repo.
