### ISSUE TITLE
How do you solve the problem of returning EOF when remotely accessing a node RPC interface?

### ISSUE THREAD

**Issue by summerxue1992** [decred/dcrd#2140]
Mandatory short links are already set for remote access.

**Comment by summerxue1992** [comment]
I hope to hear from you soon

**Comment by jrick** [comment]
I don't understand the question.

**Comment by davecgh** [comment]
There isn't much to go on here, but my guess is that you're getting an EOF when attempting to speak to the RPC server from some library and it's probably because some combination of the following things:

1) The RPC server in dcrd isn't running because you didn't configure the `rpcuser` and `rpcpass` options in the config file
2) You're accessing the wrong port -- it is 9109 by default
3) You aren't using TLS and/or the correct certificate.
4) You aren't specifying the http basic authorization headers and/or the correct values

Here is an example using curl on the command line to communicate with dcrd's RPC server:

> $ curl --silent --cacert "~/.dcrd/rpc.cert" --user "USER:PASS" --data-binary '{"jsonrpc": "1.0", "id":1, "method": "getinfo", "params": []}' https://127.0.0.1:9109

Make sure to replace `USER` and `PASS` with the user and pass of dcrd's RPC server, which you can get from the `~/.dcrd/dcrd.conf` file.


The result:
> {"jsonrpc":"1.0","result":
{"version":1060000,"protocolversion":7,"blocks":435775,"timeoffset":1,"connections":8,"proxy":"","difficulty":25341844750.367577,"testnet":false,"relayfee":0.0001,"errors":""},"error":null,"id":1}

**Comment by summerxue1992** [comment]
thanks for your answer.   Here is my access example:

curl -d '{"id":13,"method":"getblockhash","jsonrpc":"1.0","params":[100]}' https://52.198.168.7:9109 -u 111:222 -k

I  used  -k  to skip the tls verify.Block data can be retrieved correctly.

**Comment by summerxue1992** [comment]
After a while, however, the request failed and the block data could not be retrieved.

**Comment by summerxue1992** [comment]
My guess is that DCRD's RPC service shields my IP because I make frequent RPC requests to it.

**Comment by davecgh** [comment]
It's probably whatever machine you're connecting to limiting it.  dcrd does not limit the the number of requests since it requires a user/pass combination and only listens on localhost by default.

**Comment by summerxue1992** [comment]
I am a remote access RPC service.
