### ISSUE TITLE
Transaction rejected with insufficient priority

### ISSUE THREAD

**Issue by summerxue1992** [decred/dcrd#2146]
when i brodcasted a txhex with  sendrawtransaction  rpc method.  it returned me: 
'-1: rejected transaction 219c88734be2255c3662264f14018c6f7ac285fe93b6555cee5a9d3a0064eb17: transaction 219c88734be2255c3662264f14018c6f7ac285fe93b6555cee5a9d3a0064eb17 has insufficient priority (1.2535979559471365e+07 <= 5.76e+07)' 

txid : 219c88734be2255c3662264f14018c6f7ac285fe93b6555cee5a9d3a0064eb17
Can i  know  is there anything wrong  with my txhex.

**Comment by davecgh** [comment]
It's not paying enough a high enough fee, hence the error message.

**Comment by summerxue1992** [comment]
yeah，i tried to pay higher fee of the tx, it works.But i can't understand。

here are two tx  i sended.

1.   318bfc026623793e8cd8f814b5316769706621e30ad14db68f81f8de38f90233
2.  219c88734be2255c3662264f14018c6f7ac285fe93b6555cee5a9d3a0064eb17

these fee rate are the same.   0.00001 dcr/KB.
But the first was success, the second was wrong.

So  i  paied a higher fee  in the second tx, now  it works.  txid is : 352e44d5d1e6dc643de32f395d717b7458d8c3baedb6672530d69f573ce012c3 

fee rate is 0.00010245 DCR/kB

**Comment by davecgh** [comment]
The fee rate is `0.0001 DCR/KB` (aka `10000 atoms`) not `0.00001`.

However, because transactions are typically less than 1000 bytes, the absolute fee typically ends up being less than `0.0001`.

Transaction 318bfc026623793e8cd8f814b5316769706621e30ad14db68f81f8de38f90233 is 252 bytes.  Thus `(0.0001 * 252) / 1000 = 0.0000252 DCR`, which is what was paid.

The other transaction 352e44d5d1e6dc643de32f395d717b7458d8c3baedb6672530d69f573ce012c3 is 816 bytes.  Thus `(0.0001 * 816) / 1000 = 0.0000816 DCR` is the min required fee and it looks like you paid `0.0000836 DCR` which is slightly more than the min required and indeed does create a fee rate of `0.0000836 * 1000 / 816 = 0.00010245 DCR/KB` which is indeed greater than the minimum required fee rate of `0.0001 DCR/KB`.
