### ISSUE TITLE
vertify the correct pair of public and private keys with DPUB KEY?

### ISSUE THREAD

**Issue by topmati** [decred/dcrd#2603]
I am very sorry to disturb you here, because I tried many methods but still failed. When I started a decred wallet with 33 words and  four of them may be lost because of my mistake  (although it is bad, but there is still a chance to retrieve ) I  can quickly calculate the possible seeds, but this is still too slow to know which one is never used. The potential combination is still more than 1 million, so I want to find help here. I have the last  address and extended public key(dpub).Is there any way to vertify the correct pair of public and private keys with DPUB KEY? Sincerely look forward to getting your help and thank you for taking the time to read.

**Comment by davecgh** [comment]
This is really more of a wallet question than a dcrd question, but your best bet is probably to create a wallet with the seed and then use the `validateaddress` RPC (e.g. `dcrctl --wallet validateaddress D....`) and check for `ismine: true` in the output.

It's going to take a long time, especially if you only know the final address, because you'll have to wait for the wallet to discover all used addresses every time you try a new seed in order for it to know if the address in question is indeed actually yours.

Aside from that, you'd have to write custom code.

**Comment by chappjc** [comment]
>  I have the last address and extended public key(dpub)

So you have 29 of the 33 seed words, but you have the extended public keys for each account?  Sounds like you could write some Go code to generate an HD extended key from a candidate set of seed words, then derive child keys (account and branch) from the master key and see if their public keys match the dpubs you have.  You'll have to get familiar with the derivation paths to be sure you're doing it right otherwise you're going to be comparing the wrong thing.

**Comment by topmati** [comment]
> This is really more of a wallet question than a dcrd question, but your best bet is probably to create a wallet with the seed and then use the `validateaddress` RPC (e.g. `dcrctl --wallet validateaddress D....`) and check for `ismine: true` in the output.
> 
> It's going to take a long time, especially if you only know the final address, because you'll have to wait for the wallet to discover all used addresses every time you try a new seed in order for it to know if the address in question is indeed actually yours.
> 
> Aside from that, you'd have to write custom code.



> 实际上，这比dcrd问题更像是一个钱包问题，但是最好的选择可能是使用种子创建一个钱包，然后使用`validateaddress`RPC（例如`dcrctl --wallet validateaddress D....`）并`ismine: true`在输出中进行检查。
> 
> 这将花费很长时间，尤其是如果您仅知道最终地址，因为每次尝试新种子时，您都必须等待钱包发现所有使用过的地址，以使其知道所涉及的地址确实是您的。
> 
> 除此之外，您还必须编写自定义代码。

I really appreciate it。Thank you.

**Comment by topmati** [comment]
> 实际上，这比dcrd问题更像是一个钱包问题，但是最好的选择可能是使用种子创建一个钱包，然后使用`validateaddress`RPC（例如`dcrctl --wallet validateaddress D....`）并`ismine: true`在输出中进行检查。
> 
> 这将花费很长时间，尤其是如果您仅知道最终地址，因为每次尝试新种子时，您都必须等待钱包发现所有使用过的地址，以使其知道所涉及的地址确实是您的。
> 
> 除此之外，您还必须编写自定义代码。

Thanks a lot for your advise, I'll try it to fix the problem.
