### ISSUE TITLE
Can't send my dcr with ledger

### ISSUE THREAD

**Issue by posa88** [decred/dcrd#2631]
I can't send my decred, with error: data.length exceed 256 bytes limit. Got: 256 
I try to ask for help from ledger support but they seems can't help me.
Plz help..
[issue i post on ledger](https://github.com/LedgerHQ/ledger-live-desktop/issues/3478)

**Comment by davecgh** [comment]
I posted this over into the hardware wallets channel to see if maybe someone over there is able to help out, but I'm going to close it from here because it doesn't have anything to do with dcrd.  dcrd does not handle anything related to wallets, hardware or otherwise.

Based on the linked issue, it looks like a bug in the ledger live wallet to me.
