### ISSUE TITLE
proposal: Move generic packages to external repos

### ISSUE THREAD

**Issue by JFixby** [decred/dcrd#2673]
There are some packages that contain only generic code and do not directly on indirectly depend  on Decred-specific code. 

The suggestion is to move them to dedicated external repos. Like it is already done for 
```
github.com/davecgh/go-spew v1.1.1
github.com/decred/base58 v1.0.3
github.com/decred/slog v1.1.0
```

First example is ```github.com/decred/dcrd/crypto/blake256``` that has no dependencies according to go.mod as well as ```github.com/decred/dcrd/crypto/ripemd160```  Then ```github.com/decred/dcrd/bech32```, ```github.com/decred/dcrd/certgen```, ```github.com/decred/dcrd/lru``` and ```github.com/decred/dcrd/dcrec/edwards``` This is not a full list, just the most obvious candidates. 

To clarify the ```github.com/decred/dcrd/chaincfg```-package is the Decred-specific code, since it defines networks parameters, and all the packages that depend on in should remain untouched.

**Comment by davecgh** [comment]
I would very much prefer not to do that.  External repositories do not get anywhere near the review as the code in this repository and, more importantly, almost everything in the repository is fundamental to the proper operation of the consensus rules, and the few that aren't are fundamental to the proper operation of the network.

Also, they are already separated into individual modules, so external callers that only make use of e.g. `github.com/decred/dcrd/crypto/blake256` or `github.com/decred/dcrd/bech32` are not downloading everything in the repository, rather, only the modules themselves which would be the same as a separate repository.

e.g.

```bash
$ cd
$ mkdir -p ~/showblake256use/go
$ GOPATH=~/showblake256use/go
$ cd showblake256use
$ go mod init example
$ go get github.com/decred/dcrd/crypto/blake256
$ tree go/pkg/mod/github.com/decred/dcrd
go/pkg/mod/github.com/decred/dcrd
└── crypto
    └── blake256@v1.0.0
        ├── blake256.go
        ├── blake256_test.go
        ├── blake256block.go
        ├── go.mod
        ├── LICENSE
        └── README.md
```

```bash
$ cd
$ mkdir -p ~/showbech32use/go
$ GOPATH=~/showbech32use/go
$ cd showbech32use
$ go mod init example
$ go get github.com/decred/dcrd/crypto/bech32
$ tree go/pkg/mod/github.com/decred/dcrd
go/pkg/mod/github.com/decred/dcrd
└── bech32@v1.1.1
    ├── bech32.go
    ├── bech32_test.go
    ├── doc.go
    ├── error.go
    ├── example_test.go
    ├── go.mod
    ├── LICENSE
    └── README.md
```

**Comment by JFixby** [comment]
I see but for example `blake256` last edit was two years ago. And it is unlikely there will be any fundamental changes in the package. Seems like pretty finalized library that can be stored externally without any worries. As well as the others mentioned above.

**Comment by davecgh** [comment]
As an aside, I do actually plan to add to `blake256` at some point in the future to better support a much more efficient signature algorithm, but I think that really is kind of tangent since the bigger point is to look at why would it matter.

What benefit do you gain from separate repositories from a caller perspective?

Due to modules, from a caller perspective, the only actual difference would be that you would do:

```
$ go get github.com/decred/blake256
```

Instead of:
 ```
$ go get github.com/decred/dcrd/crypto/blake256
```

Similarly, the import statements change in the same way.  Otherwise, they are completely identical from a caller perspective.  They both pull in a single module (and any dependencies required by the module of course, but again, those would be the exact same between how it is and if they were in a separate repo) and updates can easily be detected with the go module tooling.

**Comment by davecgh** [comment]
I should also note that I I am **extremely** sensitive to the desire to avoid dependency graph bloat and the need to download irrelevant stuff.  Every new dependency is more code that has to be audited, even if it is only used intransitively.  As a case in point, in dcrd, the policy is that there has to be an _extremely_ good reason to even consider adding a new external dependency at this point, due to extra maintenance burden it imposes as well as the fact that very few external dependencies have the same stringent requirements that consensus code such that certain things simply can not change without breaking historical blocks and such.  All of that is just to point out that I am keenly aware of issues with dependencies.

I suspect avoiding the aforementioned is the primary motivation here for separate repositories as, prior to the introduction of go modules, including a package from repository did in fact cause the aforementioned dependency bloat.  However, now that go uses modules, it is no longer the case so long as the modules are properly maintained, which we take great care to do.

**Comment by JFixby** [comment]
OK.
