### ISSUE TITLE
[question] addBlock - boostrap.dat generation

### ISSUE THREAD

**Issue by jpbriquet** [decred/dcrd#27]
I would like to start new dcrd nodes and have a way to prevent the full blockchain synchronization.
For this purpose, I intend to use the existing addBlock utility and a bootstrap file to load the blockchain in the dcrd database.

I don't find it in documentation, is there already a way to generate or export a boostrap.dat file from a running dcrd node ?

**Comment by davecgh** [comment]
I would guess that there probably isn't a way.  I know that the upstream project upon which this one is based doesn't have a way to generate one because there are already existing Bitcoin tools for it.

However, given this is a new currency and there are no tools for it, I agree that it would be a good idea to have a tool to generate the linear, no-fork version of the block chain the `addblock` utility requires.

**Comment by jcvernaleo** [comment]
@jpbriquet what I would probably do in your case is start the node, let it sync, stop the node, drop any blocks later than what you want to be at with https://github.com/decred/dcrd/tree/master/cmd/dropafter and then restart with no peers (--connect=localhost or something like that),

I also agree that a tool to generate a bootstrap.dat like file (up to a specified block) would be nice.  showblock might be a good starting point for such a thing.

**Comment by jpbriquet** [comment]
Thanks @davecgh @jcvernaleo  for your answers 

I agree too that a new tool to dump to bootstrap.dat file would be good, and I understand that it was not needed with btcd, as it was already provided by the Bitcoin project.

At the moment, I think that I will keep a reference node synchronised. This node will be periodically stop  while its database files are saved as blockchain database snapshot.
I will push this database to new nodes in their data directory when they are started, and I hope that it will prevent the full synchronisation. (I've not tried this principle yet).

In my spare time, I may take a look about the tool.
As I'm not yet familiar with the dcrd codebase, in addition of showblock is there other related things or places where I should dig?

**Comment by davecgh** [comment]
So, you would start by using `addblock` as a skeleton for the new app `linearize` in order to get the standard config pieces and database setup.

Once that is in place, essentially you would just need to loop through all of the blocks in order and dump them out using the correct serialization format.

I just took a look and the `readBlock` function in `addblock` to see the serialization format for the `boostrap.data` file and it has the following comment: 
```Go
	// The block file format is:
	//  <network> <block length> <serialized block>
```

So, putting it all together, you would basically just need a nicer version of the following:

```Go
	_, bestHeight, err := db.NewestSha()
	if err != nil {
		log.Errorf("Failed to retrieve latest hash: %v", err)
		return err
	}

	for i := int32(0); i < bestHeight; i++ {
		// Get the block hash for the current height.
		blockHash, err := db.FetchBlockShaByHeight(i)
		if err != nil {
			// log it...
			return err
		}

		// Load the block for the current height.
		block, err := db.FetchBlockBySha(blockHash)
		if err != nil {
			// log it...
			return err
		}

		// Serialize the block.
		serializedBlock, err := block.Bytes()
		if err != nil {
			// log it...
			return err
		}

		// Write out the serialized block to the file with the expected
		// header format.
		err = binary.Write(fi, binary.LittleEndian, uint32(activeNetParams.Net))
		if err != nil {
			// log it...
			return err
		}
		err = binary.Write(fi, binary.LittleEndian, uint32(len(serializedBlock)))
		if err != nil {
			// log it...
			return err
		}
		_, err = fi.Write(serializedBlock)
		if err != nil {
			// log it...
			return err
		}
	}
```
