### ISSUE TITLE
Feature Req: Can we have a setting to throttle cpu usage on blockchain syncs?

### ISSUE THREAD

**Issue by andrewfenn** [decred/dcrd#2741]
This is a continuation of the feature request I filed in Decredition here: https://github.com/decred/decrediton/issues/3458

I would like a feature to be able to throttle the CPU usage as currently it maxes out all my cores and CPU usage. The use case for this would be when opening clients such as Decredition it would take a little longer the run through the chain while not melting my notebook. I would recommend two config options limit by cores and cpu usage if possible.

**Comment by jrick** [comment]
This doesn't need to be an application 'feature'. You can just reduce the process' priority (e.g. using `nice` on unix or task manager on windows), or perhaps limit which cpu cores the application is able to be scheduled on.

**Comment by andrewfenn** [comment]
This is something I have tried but without any success, but if there is not much interest so be it.

**Comment by jrick** [comment]
Which os are you using?

There's also an environment variable that affects all Go programs (at least their defaults, and we don't override it) called GOMAXPROCS that can be set to the number of threads an application will use.  For example, if you have 8 CPUs, but only want dcrd to run on 6 of them, you could run `GOMAXPROCS=6 dcrd` and it will never use more than 6 OS threads at a time (thereby limiting it to running on a maximum of 6 cores at once).  But this is more of a debugging feature, and perhaps not as good as the tools your OS provides to limiting scheduling.

**Comment by andrewfenn** [comment]
This was a critical issue for my older laptop with 2 cores on ubuntu. Load up Decredition and it would max out the cores running dcrd. Laptop would overheat and shutdown. On my newer laptop with Debian 11 it maxes out the 11 cores and makes the fans go crazy. It would be nice to have an option in Decredition to limit that, but I was told this is a dcrd issue. Now it seems it's an OS issue so I think without anyone taking ownership it's not really going to go anywhere.

If there is a way to do this in the OS maybe just some note in the documentation would be useful for users that aren't knowledgeable on Go options. Also not really sure how that would exactly that bubbles up to Decredition and currently i'm just using that to run dcrd.

**Comment by jrick** [comment]
Fans going crazy is not any indication of the process or the OS doing anything poorly.  This can be the result of overambitious fan curves.  Or the fan speed might be totally normal, and you just have to deal with it.  Loud fans are not necessarily an indication of a faulty userland process, or even a faulty OS.

Assuming your fan curves don't need adjustment, this is not an "OS issue" per se, but it is something that should be solvable using the tools provided by your OS.

Just like every other process in existence, dcrd will use as much resources as your OS is willing to provide it to complete the tasks it currently needs to perform.  Race-to-sleep is a very real thing, and it is in your best interest for processes to complete their tasks as quickly as possible, in order for your CPU to enter sleep mode sooner and for longer durations.

If power/heat is a concern, these resources can be limited in order to provide immediately available CPU resources for other process.  However, any decent OS scheduler, and especially one designed for minimizing input latency like on a desktop, should already handle this without any extra fiddling on your part.

Disregarding Decrediton for now, have you tried running `nice 20 dcrd` to run dcrd with the lowest possible scheduling priority? And/or have you tried using GOMAXPROCS?

P.S. a full node running on a old dual core laptop is going to suck, no matter what you or we do.

**Comment by andrewfenn** [comment]
The fans is not really the issue here and getting away from the actual premise. I should have said I observed that dcrd was maxing out in the process monitor. If GOMAXPROCs is the solution then no new feature is required just a better understanding of how to use it in relation to Decredition. I don't think it is though as my understanding from what you have described is that it just dictates how many cores a go program will make use of, not cap CPU usage on those cores. I have tried nice levels and other things. The problem with that I found is that this didn't help. As I understand it nice levels just dictate priority. It doesn't slow down dcrd from working or cap CPU usage. If you have nothing but dcrd running nice levels aren't going to do anything it's still going to max out the CPU, it's just not going to slow down your other apps while it's doing so. There are other options I can think of like perhaps using docker. From what I understand it has features to limit cpu usage, but that seems like an extreme solution that I don't see anyone using that.

**Comment by jrick** [comment]
If your hardware is shutting down due to overheating, this indicates you have poorly engineered hardware, or your fans need to spin faster.  Or whatever that might be preventing cooling as it was designed to happen (dust ingress, degraded thermal compound) needs to be removed/replaced.

It is not a software issue.

Software changes might be able to workaround the problem.  But that's not a fix.

**Comment by andrewfenn** [comment]
Yup, I've since fixed that laptop and also have a new laptop. Point of the feature is I still don't like my new laptop maxing out CPU. I'd rather it take a little longer to finish the sync. The same way you can limit FPS in games to not kill your graphics card. Hope that makes sense.

**Comment by jrick** [comment]
That is a flawed comparison. Maximizing or limiting FPS in games is attempting to maximize (or limit) the amount work done in a period of time, with no upper bound on how long it continues (it keeps happening for however long the game runs or until the system is thermal throttled).  dcrd under IDB is doing actual work though, with a finite bound, and once it has finished, the application sleeps until it has its next transaction or block to process.

**Comment by andrewfenn** [comment]
That is correct however it can typically take a very long time depending upon how far behind you are. I'd prefer not to have my laptop cooking at 100 degrees which is very normal of some high performance laptops even if it's just for 10 minutes.

**Comment by jrick** [comment]
100C temps on CPU cores is well within the engineered operational range of temperature values on modern CPUs.

If you feel this is a problem, I'm not sure what to tell you.

**Comment by davecgh** [comment]
A concrete suggestion you might be interested in is: [cpulimit](https://github.com/opsengine/cpulimit).  Since you mentioned you're using debian, you can grab it with:

`# apt-get install cpulimit`.

Then, you can do something like:

`# cpulimit --exe dcrd --limit 50`

Where that limit is the percentage of CPU usage you want to limit it to.

**Comment by andrewfenn** [comment]
@davecgh  Thanks for the suggestion. That looks perfect.
