### ISSUE TITLE
Lanch RPC server earlier during bring-up

### ISSUE THREAD

**Issue by marcopeereboom** [decred/dcrd#297]
In order to enhance the paymethues UX we need to start the dcrd.exe RPC server so that we can inform the user where things are at.

- [ ] Launch RPC server right after initial creation of certificates
- [ ] All RPC requests should be answered with "not ready" status and a status qualifier that reports which subsystems are up and which ones are not.

**Comment by jrick** [comment]
I have the RPC server starting earlier now on my "earlyrpc" branch on my btcd fork.  After discussing with marco, we've decided to use a separate pipe (with a fd set through a command line arg) for communicating which systems are up and down instead of using rpc.  The pipe uses a custom binary format for message encoding and the paymetheus launcher app won't need to include a json-rpc client to manage the lifetime of the dcrd process.

**Comment by jrick** [comment]
We've decided to not change the ordering of when the RPC server starts and only use the new pipes for parent process IPC.
