### ISSUE TITLE
Minimize changes between btcd and dcrd

### ISSUE THREAD

**Issue by marcopeereboom** [decred/dcrd#301]
We have accumulated several unfortunate and preventable, changes between code bases that make merging code back and forth too painful.  The time has come to rectify this.

The following larger changes need to be made:
- [x] Package up btcd/dcrd hash

**Comment by davecgh** [comment]
To elaborate on the issue, the following is a list of major points to be addressed:

- [ ] Backport the `chainhash` package to btcd so it is more agnostic to the hash function being used
- [ ] Backport as many of the `chaincfg.Params` consensus parameterizations as possible.  This obviously can' be a one to one correspondence since Decred has more and different rules, but there are a still a decent number of parameterizations that can be made consistent.
- [ ] Several functions where moved to other files for no good reason which causes a lot of merge conflict headaches.  These need to be reverted back to their original locations.
- [ ] Tons of functions signatures where changed to have inconsistent formatting (btcd uses a single line for function signatures whereas dcrd decided to do its own thing and split them all).  This causes constant merge conflicts for things that ordinarily be a conflict.

**Comment by cjepson** [comment]
I would prefer to avoid writing/merging the last two until the new blockchain database is merged, so avoid a huge headache rebasing that.

**Comment by davecgh** [comment]
I'm mostly done with the first one for btcd.  I'm just reviewing all of the changes again and need to open all the PRs for the various repos since it touches basically everything.

**Comment by davecgh** [comment]
Pull requests for the first item submitted upstream:

https://github.com/btcsuite/blocksafari/pull/11
https://github.com/btcsuite/btcrpcclient/pull/81
https://github.com/btcsuite/btcsim/pull/97
https://github.com/btcsuite/btcutil/pull/78
https://github.com/btcsuite/btcd/pull/729
https://github.com/btcsuite/btcwallet/pull/450

**Comment by marcopeereboom** [comment]
so i am ok with this provided we make travis happy.

**Comment by jcvernaleo** [comment]
I oked all the linked PRs (and I think I did a lot of dcrd's chainhash).  You might need some glide updates to get btcd to use the correct versions of the btcutil, etc though.

**Comment by davecgh** [comment]
@jcvernaleo Right, I'm planning on pushing the btcutil one first, and then updating the btcd PR with the appropriate glide hash so Travis will pass.

**Comment by davecgh** [comment]
All of the relevant PRs for the first item are merged upstream.  There will eventually need to be PRs which sync them down into Decred as well, but that will happen as a part of the upstream sync.

**Comment by davecgh** [comment]
Upstream PRs for the second item:

https://github.com/btcsuite/btcd/pull/732
https://github.com/btcsuite/btcsim/pull/99
https://github.com/btcsuite/btcwallet/pull/451

**Comment by davecgh** [comment]
The remaining two items will need to wait until @cjepson has finished integrating the upstream blockchain/db changes.

**Comment by davecgh** [comment]
The vast majority of this has been cleaned up.  The rest will happen via future upstream syncs.
