### ISSUE TITLE
Given a private key as a string, how will I generate a public key?

### ISSUE THREAD

**Issue by naddika** [decred/dcrd#3116]
This project is a used in Cosmos SDK as a module, right?

Given a private key as a string, how will I generate a public key - wallet - using secp256k1?

**Comment by davecgh** [comment]
I'm not familiar with the Cosmos SDK, but looking at the github repo, I do see it listed as a direct dependency in their `go.mod`, so it appears that it does use it.

For your question, it depends on what format the private key string is in.  Assuming it's just the hex-encoded bytes of the private key and is already known to be good, you'd just do the typical `hex.DecodeString` to decode the string into raw bytes and then call [`secp256k1.PrivKeyFromBytes`](https://pkg.go.dev/github.com/decred/dcrd/dcrec/secp256k1/v4#PrivKeyFromBytes) to convert it to a private key that you can then convert to a public key via the [`PubKey`](https://pkg.go.dev/github.com/decred/dcrd/dcrec/secp256k1/v4#PrivateKey.PubKey) method it exposes.  From there, you have the public key and can serialize it if you want or otherwise use it however your want.

There is an example in the `secp256k1/ecdsa` package of doing decoding a hard-coded private key string, using it to sign a message, getting the public key for it, and then verifying the signature+message with the public key:

https://pkg.go.dev/github.com/decred/dcrd/dcrec/secp256k1/v4@v4.2.0/ecdsa#example-Sign

Here is a trivial example that does only what you asked and then prints out the serialized compressed public key:

```Go
package main

import (
	"encoding/hex"
	"fmt"

	"github.com/decred/dcrd/dcrec/secp256k1/v4"
)

func main() {
	privKeyString := "0000000000000000000000000000000000000000000000000000000000000001"
	privKeyBytes, err := hex.DecodeString(privKeyString)
	if err != nil {
		fmt.Println(err)
		return
	}
	privKey := secp256k1.PrivKeyFromBytes(privKeyBytes)
	pubKey := privKey.PubKey()
	fmt.Printf("Serialized Public Key: %x\n", pubKey.SerializeCompressed())
}
```
