### ISSUE TITLE
How to convert `ecdsa.PrivateKey` to `secp256k1.PrivateKey`?

### ISSUE THREAD

**Issue by joshklop** [decred/dcrd#3449]
Right now I'm doing

```go
func convertPrivKey(ecdsaPrivKey *ecdsa.PrivateKey) *secp256k1.PrivateKey {
        key := new(secp256k1.ModNScalar)
        if key.SetByteSlice(ecdsaPrivKey.D.Bytes()) {
              panic("overflow")
        }
        return secp256k1.NewPrivateKey(key)
}
```

**Comment by davecgh** [comment]
That's close, but you're not fully properly checking the private key is in a valid range and it's potentially quite dangerous in how easily you can panic that if you're ever taking bytes from a user.  I'll elaborate on the range a bit below.

That said, I'd generally suggest starting with the private key as a `secp256k1.PrivateKey` directly, since the private key bytes have to be coming from somewhere.  Either you're generating a new one or you're loading the existing bytes in some way (from disk, user entry, coming across the wire, etc).  Your conversion here falls into the second category, but chances are you don't actually need to start with an `ecdsa.PrivateKey` to begin with, because you probably have the raw bytes.

In the case you're generating a new private key, you'd simply use [secp256k1.GeneratePrivateKey](https://pkg.go.dev/github.com/decred/dcrd/dcrec/secp256k1/v4#GeneratePrivateKey) instead of first generating an `ecdsa.PrivateKey` and converting it.

In the case you're loading existing bytes, you need to heed the warning on [secp256k1.PrivKeyFromBytes](https://pkg.go.dev/github.com/decred/dcrd/dcrec/secp256k1/v4#PrivKeyFromBytes) about the allowed private key range of `[1, N-1]`.  Specifically:

> PrivKeyFromBytes returns a private based on the provided byte slice which is interpreted as an unsigned 256-bit big-endian integer in the range [0, N-1], where N is the order of the curve.

> WARNING: This means passing a slice with more than 32 bytes is truncated and that truncated value is reduced modulo N. Further, 0 is not a valid private key. It is up to the caller to provide a value in the appropriate range of [1, N-1]. Failure to do so will either result in an invalid private key or potentially weak private keys that have bias that could be exploited. 

Your code is neither ensuring the bytes are a max of 32 bytes nor rejecting 0.

The 32-byte restriction is also repeated in the comments for [ModNScalar.SetByteSlice](https://pkg.go.dev/github.com/decred/dcrd/dcrec/secp256k1/v4#ModNScalar.SetByteSlice)

> Note that since passing a slice with more than 32 bytes is truncated, it is possible that the truncated value is less than the order of the curve and hence it will not be reported as having overflowed in that case. It is up to the caller to decide whether it needs to provide numbers of the appropriate size or it is acceptable to use this function with the described truncation and overflow behavior. 

Finally, depending on how it's used, since you're dealing with private key material, you really shouldn't have non cryptographically constant-time branches since it could be used as an oracle to perform side-channel timing attacks and, for best practices, you generally don't want to leave private key material around in extra copies to reduce the possibility for exfiltration via attacks like Spectre and Meltdown, so you should be clearing any bytes used in the temporary conversion too.

However, I'll ignore all that and stick with your (as previously mentioned, potentially dangerous) panics for the sake of illustrating the necessary range checks here since you're already in vulnerable territory in terms of the aforementioned attack vectors if you're dealing with the stdlib `ecdsa` anyway.

```Go
func convertPrivKey(ecdsaPrivKey *ecdsa.PrivateKey) *secp256k1.PrivateKey {
	privKeyBytes := ecdsaPrivKey.D.Bytes()
	var key secp256k1.ModNScalar
	if len(privKeyBytes) > 32 || key.SetByteSlice(privKeyBytes) {
		panic("overflow")
	}
        if key.IsZero() {
              panic("private keys must not be 0")
        }
        return secp256k1.NewPrivateKey(&key)
}
```

**Comment by joshklop** [comment]
Thank you for the thorough explanation. The provided solution works for me.
(I should have mentioned I am converting the private keys in a test, not in production code)
