### ISSUE TITLE
Enable chained spending of SStx change in mempool and wallet

### ISSUE THREAD

**Issue by cjepson** [decred/dcrd#5]
OP_SSTXCHANGE tagged outputs should be spendable in chains. In wallet, if the ticket has failed to enter a block, the user will not see the change tagged funds in their wallet.

**Comment by davecgh** [comment]
I'm going to close this as it would require much larger changes that would necessarily change the semantics of this opcode along with them.

For completeness, there are a couple of key considerations here:
- The stake tree can't spend from transactions in the regular tree without waiting at least one block due to the ability for the next block to invalidate those transactions, so as long as that behavior is the case, this opcode can't be changed in that regard
- The stake tree currently has no notion of dependencies in the same block, unlike the regular transaction tree and changing that would be a pretty significant consensus change that would need to touch multiple opcodes.
