### ISSUE TITLE
orphan blocks should not have confirmations

### ISSUE THREAD

**Issue by jolan** [decred/dcrd#546]
@tpruvot noticed that one of the blocks mined by yiimp was noted as having 260 confirmations but was actually an orphan.  Having confirmations set to a positive number doesn't really make much sense given nextblockhash is unset.

This behavior is inherited from Bitcoin via btcd but the behavior was changed in Bitcoin a couple years ago in this commit:

https://github.com/bitcoin/bitcoin/commit/57153d4e1ac6e2cc9fc3f2fcd6d786e9813d824f

So we should set -1 to be consistent with Bitcoin or 0 if we don't want to change from a uint64.

**Comment by davecgh** [comment]
I'd suggest changing the type to `int64` and using -1 since 0 is already a sentinel value used to mean it's in the mempool and hasn't yet been mined into a block.

**Comment by tpruvot** [comment]
yep or just remove the field ;) cant be confirmed if orphaned

**Comment by jrick** [comment]
I think it should use whatever the value is for stake-invalidated blocks (I think this is -1, but I haven't checked).

**Comment by davecgh** [comment]
While omitting the field would potentially be a reasonable choice, omitting numeric JSON fields that can also be zero is rather cumbersome in Go (it requires a pointer) because the zero value of numeric fields is 0 which means the JSON "omitempty" struct tag causes the resulting JSON to omit the field when it is 0.

Coupling that with @jrick's point, I definitely think `-1` is the best choice.
