### ISSUE TITLE
JSON RPC API version bump for getbalance?

### ISSUE THREAD

**Issue by chappjc** [decred/dcrd#553]
Shouldn't the `getbalance` change, specifically `GetBalanceResult` and `GetAccountBalanceResult` being the new result, make a JSON API version bump?  It's still 2.0.0.

I'm putting this issue here since this pertains to package dcrjson, and because it seems that the version RPC is handled in dcrd/rpcserver.go.  I'm referring to the `dcrjson.VersionResult{"dcrdjsonrpcapi": ...}`.  I sort of understand why there's no `"dcrwalletjsonapi"`, but it would be nice to have the wallet respond with something pertaining to the wallet RPCs, the ones that aren't passed through to dcrd.  Or at least bump when the wallet's responses change.

**Comment by jrick** [comment]
The way it is intended to work is that many versions can be returned in the same response.  When you query the wallet server for its api version, you should get both the dcrd and wallet versions.

Unfortunately wallet never overrode this RPC and never added its own API version, so the only result you got was for dcrd (because of RPC passthrough).

So either we could assume the previous api was version 1.0.0, and "bump" it to 2.0.0, or we can start at 1.0.0.

Either way there's no need to add anything else in this package, it would only be a change in wallet.

**Comment by chappjc** [comment]
OK, perfect.  It did seem there needed to be a response handled by wallet rather than passthrough.  I don't care what the version is, just that there's something to check.
