### ISSUE TITLE
Reset testnet

### ISSUE THREAD

**Issue by marcopeereboom** [decred/dcrd#596]
Requires #595 

We need to reset testnet because we are going to alter the voting interval.  This has to happen **after** #595 and **after** we have reached a vote on the hardfork demo (blocksize resize 1MiB->1.25MB).

I will add more details on timing etc son.

**Comment by jcvernaleo** [comment]
Since this was a fairly long discussion on irc I'm listing the steps needed for this to happen here.  If there is anything I missed, please add it in.  These steps should be pretty much independent of the actual timeline for it so I'll leave any timeline info to @marcopeereboom.

1. - [ ] HF vote demo is complete.
1. - [ ] PR for #595 is done.  It will need to be reviewed, but NOT merged to master.
1. - [ ] PR on top of that with any extra changes needed (change name to testnet2 maybe, not sure if anything else belongs here).  This also must be reviewed but NOT merged.
1. - [ ] Some of our testnet nodes and miners will move to the new code (@jolan and I at least, probably @alexlyp too).
1. - [ ] Above PRs are merged into master.
1. - [ ] Remaining testnet infrastructure (block explorer, webwallet, remaining nodes and miners that we control, faucet, anything else) are moved to the new testnet.
1. - [ ] Additional PRs and work happens.
1. - [ ] Normal release happens.

**Comment by jcvernaleo** [comment]
Updating this to point out the progress.  Current plan is for the actual reset to happen on 03/15/2017

**Comment by jcvernaleo** [comment]
HF vote demo is done and succeeded.

**Comment by jcvernaleo** [comment]
The dcrd testnet work is in #617 and for wallet decred/dcrwallet#610

**Comment by jcvernaleo** [comment]
And the PR for the seeder decred/decred-seeder#7

**Comment by jcvernaleo** [comment]
Nodes, seeders, insight have all been moved to testnet2.

**Comment by jcvernaleo** [comment]
Looks like everything was moved over (and the last two points on the checklist are related to the release, not to testnet and were just there to show the full plan.  So closing.

**Comment by jcvernaleo** [comment]
For future reference we also need to update bitcore for webwallet work when we do this.  See decred/bitcore#6
