### ISSUE TITLE
PoS missed ticket locked

### ISSUE THREAD

**Issue by kallisti5** [decred/dcrd#611]
Good afternoon,

I *think* i have funds locked in a ticket that I can't recover for some reason.  Really old wallet with a lot of PoS.  I currently have one pool live ticket, anything else should be just voted or missed.

I'm pretty sure the imported is the pool, the big question is the 17.228 locked by tickets:

This command is what gave me the idea that something was wrong:
```
./dcrctl --wallet gettickets 1 >temp;for line in `./dcrctl --wallet missedtickets|grep ","`;do cat temp|grep $line;done
    "a81f765e101ce9e13d9d862092a9cd0b23dabb5d6e2c070272e47a6a8c20d199",
```

I tried a rebroadcastwinners and rebroadcastmissed without any progress.

Balances:
```
{
  "balances": [
    {
      "accountname": "default",
      "immaturecoinbaserewards": 0,
      "immaturestakegeneration": 0,
      "lockedbytickets": 17.22897614,
      "spendable": 76.51572727,
      "total": 93.74470341,
      "votingauthority": 0
    },
    {
      "accountname": "imported",
      "immaturecoinbaserewards": 0,
      "immaturestakegeneration": 0,
      "lockedbytickets": 36.66956117,
      "spendable": 0,
      "total": 36.66956117,
      "votingauthority": 0
    }
  ],
  "blockhash": "00000000000006dff6f57a347095ceb5aa110441a20de06e719647159d1f37e3"
}
```

**Comment by kallisti5** [comment]
```
$ ./dcrctl --wallet getstakeinfo
{
  "blockheight": 113844,
  "poolsize": 41150,
  "difficulty": 60.60674755,
  "allmempooltix": 1,
  "ownmempooltix": 0,
  "immature": 0,
  "live": 1,
  "proportionlive": 2.4301336573511544e-05,
  "voted": 13,
  "totalsubsidy": 22.37526804,
  "missed": 12,
  "proportionmissed": 0.48,
  "revoked": 11,
  "expired": 0
}
```

**Comment by davecgh** [comment]
I'm sure you've already resolved this via slack, but I'll post the details here as well for reference.

In order to get them revoked, please do the following:

- Start the wallet process with the `--enablevoting` flag.  It will not issue revocations without it.
- Unlock the wallet with `dcrctl --wallet walletpassphrase "yourpassphrase" 0`.  The wallet must be unlocked for it to be able to create the revocations and sign them.
- Instruct dcrd to notify the wallet about missed tickets again so it will issue the revocations with `dcrctl rebroadcastmissed`.

At that point, you should see the wallet log some details about the revocation transactions.  Once those revocation transactions are mined into a block (which should be the next block), you will see the funds move to the `immaturestakegeneration` category in the `dcrctl --wallet getbalance` output.  Finally, after 256 blocks, they will move to `spendable` category and thus be available to spend.

NOTE: You could also just wait for a new block to show up for the final step since the wallet will automatically issue revocations given the first two conditions are true, but I suggested you manually issue the notification so you can more easily verify it issues the revocations.
