### ISSUE TITLE
--connect and header downloads

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrd#614]
Based on our work with testnet the last few days it looks like if you startup dcrd with --connect to point to a single node, the header downloading never happens.

I think --connect worked in the past since we used it extensively in the early testnet days and for simnet.

**Comment by jpz** [comment]
I found I had a similar problem in testing - an isolated server stop send the headers to the requesting process.  I found the reason was here, with the isCurrent() check.

It would be useful in some contexts, testing for instance, to be able to disable this behaviour.

https://github.com/decred/dcrd/blame/1955bb1bf1bb84acf8223d483da09a468bc0945d/server.go#L833
