### ISSUE TITLE
"unlocked until" is not reporting anything

### ISSUE THREAD

**Issue by ocminer** [decred/dcrd#66]
I'd like to implement some security measures and check the "unlocked until" value on a regular basis of the daemon but it seems this field is unused - it always returns "0", no matter how long I unlock the wallet.

**Comment by alexlyp** [comment]
Ah so after looking at the GetInfo rpc implementation:
https://github.com/decred/dcrwallet/blob/master/rpc/legacyrpc/methods.go#L584-L586

So this would be impossible to implement without completely rewriting the unlocking mechanism.

There are upstream changes in btcwallet that will be making there way into dcrwallet at some point.  Essentially there will be no long term unlock, where each will command will unlock, do the command, then lock the wallet immediately.  

I will keep this issue open, but due to the changes that are coming this is low prio for now.

**Comment by tpruvot** [comment]
please, if "impossible", at least remove the wrong info (the line in getinfo)

**Comment by dajohi** [comment]
This really belongs in decred/dcrwallet

**Comment by dnldd** [comment]
@davecgh I think this issue should be closed since it's dcrawallet related, not dcrd.
