### ISSUE TITLE
dcrctl shows unsupported commands (e.g., move)

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrd#682]
This was brought up in the docs survey, but it belongs here.  There are unsupported commands in dcrctl (from dcrjson) that should probably be either removed or at least marked clearer.  Since we generally only add new things to the grpc api it is much less likely that we are going to go back and add in a lot of those.

**Comment by jrick** [comment]
Here are the dcrd unimplemented RPC methods (excluding getblocktemplate which is temporarily disabled)

* estimatepriority
* getblockchaininfo
* getchaintips
* getnetworkinfo

And for dcrwallet:

* backupwallet
* getwalletinfo
* importwallet
* listaddressgroupings
* dumpwallet
* encryptwallet
* move
* setaccount

I'm up for removing all of the support for the unused wallet methods (unlike btcrpcclient, we can remove these since there is no software out there that they are useful for).

We need to decide if all of the dcrd methods can be removed or if any of them should be kept around.

**Comment by Yashiroo** [comment]
`dcrctl --wallet walletinfo` gives me `-1: Chain RPC is inactive`
Could it be related to this?

**Comment by dnldd** [comment]
@jrick I think this issue should be closed, #795 removed the types listed in this issue as well.
