### ISSUE TITLE
Add RPC to query tickets as of an arbitrary block

### ISSUE THREAD

**Issue by jrick** [decred/dcrd#777]
We have an RPC to query the ticket pool at the current block but nothing exists that can query the ticket pool at an arbitrary block.  While expensive to calculate, this will be desirable for some upcoming features.

**Comment by chappjc** [comment]
This sounds good, except I would request that certain functionality not be broken in implementing it.  Specifically, I have handled the problem of computing pool value by building a stake database with a live ticket cache to minimize redundant calls to getrawtransaction, plus the following types:

- "github.com/decred/dcrd/blockchain/stake": `*stake.Node`
- "github.com/decred/dcrd/database": `database.DB`

...and the various functions in package stake, like `stake.InitDatabaseState`, `stake.LoadBestNode`, `stake.WriteDisconnectedBestNode`, etc.

The code that mainly deals with this is https://github.com/dcrdata/dcrdata/blob/master/stakedb/stakedb.go.

Please let me know if any of your planned changes will touch these packages.  Thanks!

**Comment by marcopeereboom** [comment]
Politeia needs to be able to lookup the live ticket pool for every arbitrary blockhash. Add an indexer that allows one to recreate the live ticketpool. This needs to be a two staged process.

Stage 1: Create a full index that stores all information
Stage 2: Store only differences (some sort of running journal)

We need stage 1 in order to verify stage 2. So write a brute force, use all the memory/disk version first that can then be used to cross verify the smaller optimized version.

**Comment by jrick** [comment]
Just brainstorming but there's another solution for politeia that doesn't require dcrd to keep the snapshots:

Politeia needs ticket pool snapshots but it does not necessarily require dcrd to store this info.  Instead, it could keep all of the snapshots itself (may need some new RPCs to query what tickets are added and picked each block, worse case all blocks are fetched and politeia discovers this itself).  The main problem with this though is that there is no way for users to verify for themselves that the ticket pool snapshot was correct, and that is what this issue was originally created for.  However, there is another solution that can be implemented in the future when additional header commitments are introduced by committing the ticket pool merkle root.  Then users will be able to verify the snapshot by first querying the snapshot used by politeia, and then checking that the ticket pool snapshot commitment is indeed part of the PoW-validated header commitment on their local dcrd.

**Comment by marcopeereboom** [comment]
Also how do we deal with missed notifications?  This is imo pretty error prone.

**Comment by davecgh** [comment]
Closing this since it no longer applies because Politiea acquires the information it needs via other means.

Also, for a bit of context, the primary reason a different approach was taken is that it would be incredibly expensive to acquire that information with the current implementation due to how the information is stored.  In order to support something like this with a reasonable level of efficiency, the way tickets are tracked and stored would need to be changed.
