### ISSUE TITLE
Windows builds wont run as service

### ISSUE THREAD

**Issue by ByronAP** [decred/dcrd#84]
When running as a service the main function exits the app, obviously there was some intended behavior here but for the life of me can not figure out why? This causes the service controller the toss an error instead of just allowing it to run.
https://forum.decred.org/threads/dcrd-wont-start-closes-right-away-with-error.1260/

https://github.com/decred/dcrd/blob/master/dcrd.go

**Comment by ByronAP** [comment]
I commented out the exit command after if isService and it now runs properly

**Comment by ByronAP** [comment]
I would make a pull but I don't yet know why or if this was the intended behavior.

**Comment by chappjc** [comment]
Don't go that route.  As the comment above those lines seems to indicate, the exit is to stop it from starting another instance if it detects dcrd running already as a windows service.  The idea is to start and stop if from the service control manager.

See https://github.com/decred/dcrd/blob/master/service_windows.go for how the Windows service is setup.

```
const (
	// svcName is the name of dcrd service.
	svcName = "dcrdsvc"

	// svcDisplayName is the service name that will be shown in the windows
	// services list.  Not the svcName is the "real" name which is used
	// to control the service.  This is only for display purposes.
	svcDisplayName = "Dcrd Service"

	// svcDesc is the description of the service.
	svcDesc = "Downloads and stays synchronized with the decred block " +
		"chain and provides chain services to applications."
)
```

The service would be installed by a .msi, but since those aren't available, you'll have to install it with the right command line.  See https://github.com/decred/dcrd/blob/master/service_windows.go#L275

**Comment by jcvernaleo** [comment]
Does someone who has access to windows (@jrick, @jolan, @davec maybe?) want to either confirm or comment on this?

**Comment by ByronAP** [comment]
I comment out the exit on every release and build/run it without it and I now have no problems running it as a service. I have to assume that no one else runs windows servers. I run and control all my wallets on Windows Servers using always up as a helper, works great and checks the wallet status and performs other monitoring duties with minimal hassle.

**Comment by ByronAP** [comment]
Ahh thats the problem.... I don't install windows_service.go instead I run the dcrd without running an installer.
