### ISSUE TITLE
[suggestion] Alternative SPV design, blockchain compaction and merkle B-Tree

### ISSUE THREAD

**Issue by annawaw** [decred/dcrd#978]
## Summary
I'd like to suggest/discuss an alternative SPV design that does not rely on "proof of inclusion", but rather a "proof of state".  That is, a system that uses merkle B-Tree database of unspent outputs, and includes the root hash of such tree as part of block headers in the blockchain. 

This in theory should allow SPV client to provably query full nodes for unspent outputs. It would also allow to perform blockchain compaction (if ever needed?) by only keeping information about unspent outputs, rather than entire transaction history.

## Motivation
My undestanding is that the currently used SPV systems use blockchain headers, merkle trees over transactions and proof of inclusion to verify that a transaction has taken place. However one of the flaws of this system is that is difficult to obtain a proof that the output of a transaction was not spent, or to obtain the proof that all relevant transactions have been returned.

Specifically, a malicious node may be able to make SPV node believe that a wallet has higher (or lower?) balance, by providing some incoming transactions (with proof of inclusion), but hiding outher outgoing (and maybe incoming as well?) transactions.

## Proof of state based SPV
Ideally an SPV node that wants to accurately compute balance of the wallet, would like to make queries in form "list all unspent outputs with address XYZ" or more generally "list all an unspent outputs with script ABC" (and also possibly supporting bloom filters for performanc tradeoffs). 

In a system where a correctness of the response to such queries can be proven, an SPV node would know that the computed balance is correct.

## Construction of proof of state system

Consider a deterministic state machine associated with a blockchain, where each block advances the state machine forward. The internal state of such state machine could be defined/constructed in many ways:
1) A collection of all transactions.
   If indexed, may allow for fast queries about transactions. Matching inputs to outputs. Possibly other uses.
   
2) A collection of all unspent outputs
   If indexed by output script, would allow queries about unspent outputs for SPV. Could also be used as compacted snapshot of a blockchain, assuming that number of unspent outputs is much smaller that number of all transactions.

Let's consider storing a collection of all unspent outputs, as a merkle B-Tree, that is a B-Tree that also stores a hash for each node/page. An unspent output script could be used as a record key.
If a merkle B-Tree shape is deterministic (i.e. ordered keys + fixed page size), then it would offer following properties:
1) A hash of the root node uniquely identies all collection of unspent outputs.
2) It's possible to prove presence or absence of a key (unspent output) in a tree. By returning the path as a proof.

Let's also assume (for now) that computing such tree was cheap and it was possible to compute it for each block in the blockchain. In such case it would also be possible to include a hash of the root node of in each block header.

A blockchain like that would allow:
1) An SPV client, that downloaded all block headers, to provably retrieve a state of all outputs that it is interested in.
2) Full nodes to discard the transaction history before block height X, and only keeping the information of unspent outputs at the height X (which would be secured by keeping the hash in the block header)
3) Verification of the merkle B-Tree hash, by just rebuilding it and comparing the hashes.

A possible variants, that could lessen the burden of computing entire B-Tree for each block:
a) Include the B-Tree hash only every N block (i.e. every 256 blocks)
b) Include the B-Tree hash of a B-Tree shapshot at block height: current - N (i.e. 256 blocks in the past) - this would give nodes more time to compute the B-Tree.

With both variant a) and b) and N block delay, an SPV client would only need to download recent N blocks to prove the state of the output.

**Comment by jrick** [comment]
There are a few of concerns that I have with this design:

1. Privacy seems to be reduced to be that not so dissimilar from SPV performed with bloom filtering, since transaction outputs would be queried directly from a node.  Block inclusion proofs don't suffer from this problem since the entire block is fetched when it may contain a match.

2. In order for a full node to serve up historical UTXO sets, a transaction index must be maintained.  This is how btcd used to operate several years ago (first the transaction was looked up, and then whether an output was marked as still unspent) instead of maintaining only the index of the current unspent outputs as of the main chain tip block.  The transaction index method is significantly more expensive, and while it remains in btcd and dcrd, it is not enabled by default anymore.

3. If only the UTXO set as of the best block is served to a wallet during seed restore, it will not be possible to take advantage of the BIP0044 gap limit to reduce how many addresses must be generated and checked.  For example, if the default gap limit of 20 is used, and 21 addresses have been used by the wallet, and the 21st address is the only address that received any output in the UTXO set, it is not guaranteed that any addresses will be recreated during seed restore since none of the first 20 are relevant to the UTXO set.

In addition to these concerns, I'd like to address this with regards to our plans for compact filtering:

> My undestanding is that the currently used SPV systems use blockchain headers, merkle trees over transactions and proof of inclusion to verify that a transaction has taken place. However one of the flaws of this system is that is difficult to obtain a proof that the output of a transaction was not spent, or to obtain the proof that all relevant transactions have been returned.

When a transaction spends an output that the wallet is tracking, that output is part of the data used to create the compact filter for that block containing the spending transaction, and the wallet will know that it must check the block for any relevant transactions.  Because the compact filter will be committed to the block header, and validated with PoW, it will not be possible to fool a wallet into believing a spent output is unspent unless the wallet never receives the block.

There are definite upsides to this proposal though, and that is that a wallet that does not care about historical data (and has other means to check for address usage during seed restoring) is quickly able to synchronize with the network.  It can also be used by wallets such as dcrwallet as a final verification step that all outputs believed to be unspent (by other mined transactions) actually are included in the UTXO commitment of the best block.

**Comment by annawaw** [comment]
It may be possible to mitigate some of the concerns:
1. Privacy. A full node would be expected to return entire pages of data that contain a match, rather than individual transactions. I'm also assuming that the specified UTXO filter has similar selectivity to filter used in inclusion proof.

2. For just SPV purposes, there should be no need to serve historical UTXO sets, since SPV clients are usually only interested in the most recent state. Or am I missing soemthing?

3. Agreed, UTXO set would not be able to answer whether an output was ever used. It may be possible to change the entire index, and rather than storing just unspent transaction outputs, it could store all transaction outputs. For example an index with records in a form like (TXO, created by TXID, spent by TXID, amount) would allow SPV client to find out all addresses that were used (with respect to gap).
It would also allow SPV to list all incoming/outgoin transactions, rather than just balance.

>Because the compact filter will be committed to the block header, and validated with PoW, it will not be possible to fool a wallet into believing a spent output is unspent unless the wallet never receives the block.
I'm not sure I understand that correctly. Does it mean that every SPV node query ends up being recorded in the blockchain?

**Comment by jrick** [comment]
> I'm not sure I understand that correctly. Does it mean that every SPV node query ends up being recorded in the blockchain?

No, and I think there's some confusion around the compact (or committed) filtering method we plan to use.

Our planned implementation (it's not really ours, but is being adapted from https://github.com/Roasbeef/bips/blob/master/gcs_light_client.mediawiki) filters entirely on the client (wallet) side, using a filter commitment in the block header to check for inclusion.  If the filter matches, then the wallet fetches the entire block and searches through it for any relevant transactions.  The filter commitment is made up of not only output scripts (which allow searching for transactions paying to some address) but also the previous outputs being referenced as inputs.  This means a wallet is capable of checking if a block possibly spends any unspent output, and the only way to hide this fact from the wallet would be to never serve the block.  Blocks can be fetched from any peer, not just the one that originally served the matching filter, and forged blocks can be detected so there's little risk in a spent output ever being misbelieved to be unspent.

This implementation has privacy advantages, since wallet data (UTXOs and addresses) are never served in any way to remote peers and all filtering is done on the wallet side by comparing wallet data against the committed filter.

As for wallets saving historical data, this is important for a variety of reasons (auditing, submitting tax forms, etc.) and on a practical note, our current wallet (dcrwallet) saves all relevant transactions.  It would be quite an overhaul to modify it to work with just a rolling UTXO set, and also make it impossible to freely switch between SPV and full validation mode (with dcrd RPC).

**Comment by annawaw** [comment]
Thanks for pointing to the BIP, I was not aware of it, was a very interesting read.

The compact filter chain solution, may require that entire (although smaller) filter chain is downloaded, but as long as the chain is not prohibitively large, it looks like a reasonable tradeoff between download-size vs privacy.

I wonder, if it would be possible to build an index on top of compact filter chain, to allow to reduce the set of filters that need to be downloaded. 

I.e. consider something similar to a skip list, where nodes with rank k, additionally aggregates 2^k of block compact filters. 
The probability of false positive would increase with a rank, but it also take just a single miss, to exclude entire range of compact filter blocks that would be considered for download.

**Comment by jrick** [comment]
Luckily the filter chain is only needed by Bitcoin and others that are unable to make a hard fork.  We plan on adding a commitment for the filter (hence the name committed filters) in the header itself (#971) so it won't be necessary to have a second chain just for filters -- headers are already chained.  The only gotcha here is that the first block when the fork activates will also need to include additional commitments for all previous compact filters, or else these would be completely unverified.

**Comment by annawaw** [comment]
Makes perfect sense. 

Regarding privacy concerns (i.e. with bloom filters). Is the problem related to the fact the a single node sees entire query? 
If a query was distributed to multiple nodes or other sources, would it still be a problem?

Example:
Client wants to reconstruct a subtree of a tree. It queries a peer P1 for a root and it's children. Then queries a peer P2 for a children of node A, then queries peer P2 for a children of node B, and so on... 

A peer would be able to record that client asked question about tree node N, but it would not be able to figure out how narrow or how wide the entire query was (i.e. a client could've been enumerating entire tree, but that peer only saw one question).

**Comment by jrick** [comment]
Even if you divide what data you request or what filters you send to different nodes across the network, you are still giving those nodes a very good picture of at least part of your wallet.  Server-side bloom filtering is particularly bad at this as it suffers from the problem of needing to reload the filter periodically when the false positive rate becomes too high, since the server automatically expands the filter to match all outputs created by a matching transaction, as any of them may be relevant to the wallet.  When the filters are reduced, it becomes clearer which outputs are relevant to the wallet.

**Comment by annawaw** [comment]
Closing, since:
1) GCS based SPV addresses the problem of hiding transactions.
2) #917 already suggests supporting commitments in the blockchain for alternative proofs.

**Comment by xaur** [comment]
@annawaw I think you mean #971
